apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Rahik-IF/argocd-demos.git
    targetRevision: main
    path: app_of_apps/apps

  destination:
    server: https://192.168.64.7:33893
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
